### PR TITLE
Improve zh-TW locale

### PR DESCRIPTION
**Pull request by KrasnayaPloshchad**

### CODE REVIEW

**Comment by darktrojan** [comment]
Could you explain the difference? I have no problem taking the change, I'm just curious :-)

**Comment by Arthur2e5** [comment]
Even as a zh_CN speaker, I know that the TW guys use 资料 for data, instead of 数据…

**Comment by Vdragon** [comment]
As a zh_TW speaker, I agree with @Arthur2e5

**Comment by KrasnayaPloshchad** [comment]
囧rz

**Comment by Vdragon** [comment]
@KrasnayaPloshchad I believe there's a "Close Pull Request" button below ;)

**Pull request closed without merging**
