### PR TITLE
Clone de translation from en

### PR DESCRIPTION
**Pull request by private-lock**
I've no idea, how to test this.

But since I only changed the Strings, I hope it'll work out just fine anyway.

### CODE REVIEW

**Comment by darktrojan** [comment]
Load your changed copy using `about:debugging` to test it.

**Comment by private-lock** [comment]
Ahhhhh ... never done this before ... but yes, I got to see my translations. But the icons are broken:
https://s17.postimg.org/qeq73c4un/Screenshot_20171113_104649.png
Any idea?

**Comment by darktrojan** [comment]
That confused me for a moment, but then I worked out why. The icons aren't stored in this git repo. Nothing to worry about.

**Comment by private-lock** [comment]
Ugh ... removing the temporary installation, so I go back to official release channel, kills my configuration. It's blank again.

BTW about:openwith (seen in Screenshot) does not work in Firefox:
https://addons.cdn.mozilla.net/user-media/previews/full/136/136662.png?modified=1401134835

And I can't find an option to directly integrate the buttons into the toolbar as in:
https://addons.cdn.mozilla.net/user-media/previews/full/136/136650.png?modified=1401134833

**Pull request merged**
