### PR TITLE
Small updates in polish translation

### PR DESCRIPTION
**Pull request by Qrzysio**
Mostly grammar changes.

### CODE REVIEW

**Comment by darktrojan** [comment]
Hello, thanks for your pull request. I have some comments.

Firstly, the `openwith.dtd` and `openwith.properties` files are obsolete and days away from being removed. So I won't be taking those changes.

Secondly, don't turn `…` into `...`. The character exists for the purpose I'm using it for.

Also, I'm going to tag in the original author of this translation for their opinion, because I don't speak Polish. :-) @Matthaiks, what do you think of these changes?

**Comment by Qrzysio** [comment]
Thank you. In `dtd` and `.properties` files three dots `...` have also been used. No problem to follow your rules anyway. Waiting for @Matthaiks then.

**Comment by Matthaiks** [comment]
I'm fine with those changes in the messages.json. I would move the comma placed after "darowizna" to after "najmniejsza" in _update_message_, though.

**Comment by Qrzysio** [comment]
Dots are back + comma has been moved as Matthaiks suggested.

**Pull request merged**
